version = 0.1
[default.deploy.parameters]
stack_name = "test-stack"
s3_bucket = "lex2-bucket"
s3_prefix = "zip"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MyParam=\"MyParamValue\" VpcAllowedSecurityGroupIdParameter=\"sg-0000111122223333\" VpcEndpointSubnetIdsParameter=\"subnet-0000111122223333 \""
