name: fourth-activitytypes-Action
on:
  pull_request:
    types:
     - opened
     - closed
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Get context object
          run: echo "${{toJSON(github)}}"
